mood_mapping = {
    "joy": "happy",
    "happy": "happy",
    "low": "sadness",
    "sadness": "sad",
    "bored": "disappointment",
    "anger": "angry",
    "fear": "sad",
    "surprise": "surprise",
    "neutral": "neutral",
    "bore": "bored",
    "love": "nostalgic",
    "calm": "joy",
    "excitement": "excitement",
    "caring": "caring",
    "admiration": "admiration",
    "disappointment": "disappointment",
    "confusion" : "confusion",
    "annoyance": "annoyance",
    "amusement": "amusement",
    "disapproval": "disapproval",
    "disgust": "disgust",
    "embarrassment":"embarrassment",
    "fear": "fear",
    "gratitude": "gratitude",
    "anger" : "angry",

    

}
